### ISSUE TITLE
[REQUEST] Add support of getApplicationList

### ISSUE THREAD

**Issue by GreenSnakeLinux** [avinash311/sony-tv-remote#2]
Hello,

Can you add a button to see all available applications on the TV ?
The API is getApplicationList, here is the info:
https://pro-bravia.sony.net/develop/integrate/rest-api/spec/service/appcontrol/v1_0/getApplicationList/index.html

thanks

**Comment by avinash311** [comment]
That would not fit in with this app since it requires using the REST API, while this app uses the IRCC-IP API (remote control commands).

https://pro-bravia.sony.net/develop/integrate/ip-control/index.html

Even if we did add the REST API getApplicationList to this app, would that be enough? To launch an app or create custom commands would require supporting even more REST APIs such as setActiveApp/terminateApps.

If just getApplicationList would be useful, let me know and could add just that to the Help page next to the current Get TV Remote Controller Info button.

**Comment by GreenSnakeLinux** [comment]
Yes, getApplicationList will be enough, next to Get TV Remote Controller Info would be great :)

**Comment by avinash311** [comment]
This is now available. A new tab REST API has been added. It has getApplicationList hardcoded, and also has a form to allow manual entry of any command in the Sony TV API.
